/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.pelk.findhospital.frames;

import br.com.pelk.findhospital.backend.services.ScheduleService;
import br.com.pelk.findhospital.backend.services.UserService;
import br.com.pelk.findhospital.exceptions.ScheduleNotFoundException;
import br.com.pelk.findhospital.exceptions.UserNotFoundException;
import br.com.pelk.findhospital.models.Appointment;
import br.com.pelk.findhospital.models.Doctor;
import br.com.pelk.findhospital.models.Schedule;
import br.com.pelk.findhospital.models.User;
import br.com.pelk.findhospital.tablemodels.AppointmentDoctorTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eric
 */
public class Admin2Frame extends javax.swing.JFrame {

    private String date;
    private AppointmentDoctorTableModel appointmentDoctorTableModel;
    /**
     * Creates new form Admin2Frame
     */
    public Admin2Frame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("FindHospitals - Agenda");
        setComponents();
        setDataTable();
    }

    public Admin2Frame(String date) {
        this.date = date;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("FindHospitals - Agenda");
        this.appointmentDoctorTableModel = new AppointmentDoctorTableModel();
        this.tableAppointments.setModel(appointmentDoctorTableModel);
        setComponents();
        setDataTable();
    }
    
    private void setComponents() { 
        this.lblDayDate.setText("Dia " + this.date);
    }
    
    private void setDataTable() { 
        ArrayList<Appointment> appointments = new ArrayList<>();
        User userLogged = UserService.getUser();
        for (Schedule schedule : ScheduleService.getSchedules()) {
            for (Appointment appointment : schedule.getAppointments()) {
                try {
                    LocalDateTime ldt = appointment.getAppointmentDate();
                    String dateAp = ldt.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                    Doctor doctor = (Doctor) UserService.getUser(appointment.getDoctor());
                    if(dateAp.equalsIgnoreCase(this.date) && doctor.getId().equalsIgnoreCase(userLogged.getId())) {
                        appointments.add(appointment);
                    }
                } catch (UserNotFoundException ex) {
                    Logger.getLogger(Admin2Frame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        appointments.sort((o1, o2) -> {
            return o1.getAppointmentDate().compareTo(o2.getAppointmentDate());
        });
        this.appointmentDoctorTableModel.setList(appointments);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAppointments = new javax.swing.JTable();
        lblDayDate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tableAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"13:00", "Joao"},
                {"14:00", "Pedro"},
                {null, null},
                {null, null}
            },
            new String [] {
                "Horario", "Paciente"
            }
        ));
        jScrollPane1.setViewportView(tableAppointments);

        lblDayDate.setText("Dia dd/mm/aaaa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblDayDate)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDayDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar Dia");

        jButton3.setText("Finalizar Consulta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminFrame adm = new AdminFrame();
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedIndex = this.tableAppointments.getSelectedRow();
        System.out.println(selectedIndex);
        if (selectedIndex < 0) return;
        Appointment appointment = this.appointmentDoctorTableModel.getValueAt(selectedIndex);
        ArrayList<Schedule> schedules = ScheduleService.getSchedules();
        for(Schedule s : schedules) {
            if (s.getAppointments().contains(appointment)) {
                s.getAppointments().remove(appointment);
                try {
                    ScheduleService.editSchedule(s);
                    JOptionPane.showMessageDialog(this, "Consulta finalizada com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                    this.setDataTable();
                } catch (ScheduleNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao cancelar consulta, consulte um administrador!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(ConsultaFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDayDate;
    private javax.swing.JTable tableAppointments;
    // End of variables declaration//GEN-END:variables
}
