/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.pelk.findhospital.frames;

import br.com.pelk.findhospital.backend.services.ScheduleService;
import br.com.pelk.findhospital.exceptions.ScheduleNotFoundException;
import br.com.pelk.findhospital.models.Appointment;
import br.com.pelk.findhospital.models.Clinic;
import br.com.pelk.findhospital.models.Doctor;
import br.com.pelk.findhospital.models.Hospital;
import br.com.pelk.findhospital.models.Schedule;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eric
 */
public class ConfirmarConsultaFrame extends javax.swing.JFrame {

    private Hospital hospital;
    private Clinic clinic;
    private Doctor doctor;
    private Appointment appointment;
    private AgendaMedicoFrame agendaMedicoFrame;
    
    public ConfirmarConsultaFrame() {
        initComponents();
        setTitle("FindHospitals - Confirmar Consulta");
        setLocationRelativeTo(null);
    }
    
    public ConfirmarConsultaFrame(AgendaMedicoFrame agendaMedicoFrame, Hospital hospital, Clinic clinic, Doctor doctor, Appointment appointment) {
        setLocationRelativeTo(null);
        this.agendaMedicoFrame = agendaMedicoFrame;
        this.hospital = hospital;
        this.clinic = clinic;
        this.doctor = doctor;
        this.appointment = appointment;
        initComponents();
        setComponentsData();
        
    }

    private void setComponentsData() {
        lblHospitalName.setText(hospital.getName());
        lblClinicName.setText(clinic.getSpecialization());
        lblDoctorName.setText(doctor.getName());
        LocalDateTime localDateTime = appointment.getAppointmentDate();
        String date = localDateTime.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String hour = localDateTime.format(DateTimeFormatter.ofPattern("HH:mm"));
        lblDate.setText(date);
        lblHour.setText(hour);
        lblLocation.setText(hospital.getLocalization().toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        lblClinicName = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblHour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar Consulta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 40));

        jLabel2.setText("Clinica:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel3.setText("Médico:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel4.setText("Data:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 42, -1));

        jLabel5.setText("Hospital:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 55, -1));

        jLabel6.setText("Localização:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel7.setText("Horário:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 63, -1));

        lblHospitalName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHospitalName.setText("placeholder");
        getContentPane().add(lblHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 151, -1));

        lblClinicName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClinicName.setText("placeholder");
        getContentPane().add(lblClinicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 151, -1));

        lblDoctorName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDoctorName.setText("placeholder");
        getContentPane().add(lblDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 151, -1));

        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate.setText("placeholder");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 151, -1));

        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLocation.setText("placeholder");
        getContentPane().add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 129, -1));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        lblHour.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHour.setText("placeholder");
        getContentPane().add(lblHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 129, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            Schedule schedule = ScheduleService.getSchedule(clinic.getScheduleId());
            schedule.addAppointment(appointment);
            ScheduleService.editSchedule(schedule);
            JOptionPane.showMessageDialog(null, "Confirmado", "Consulta Confirmada", JOptionPane.WARNING_MESSAGE);
            agendaMedicoFrame.dispose();
            this.dispose();
            TelaPrincipalFrame tl = new TelaPrincipalFrame();
            tl.setVisible(true);
        } catch (ScheduleNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro no sistema, contate um administrador!", "Erro!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ConfirmarConsultaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        agendaMedicoFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarConsultaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarConsultaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarConsultaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarConsultaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarConsultaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblClinicName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblLocation;
    // End of variables declaration//GEN-END:variables
}
